modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://github.com/Evoslab/Cookielicious/issues"
[[mods]]
modId="cookielicious"
version="1.2.2"
displayName="Cookielicious"
logoFile="cookielicious.png"
credits="Evo, Stardust, AvocadoSpud, Nary, EltrutLikes"
authors="Evo's Lab"
description='''
Cookielicious is an addon for Neapolitan that adds more cookie themed items.
'''
itemIcon="cookielicious:sandwich_cookie"
configBackground="cookielicious:textures/blocks/cookie_tiles.png"

[[dependencies.cookielicious]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="neapolitan" 
    mandatory=true 
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.cookielicious]]
    modId="differentiate"
    mandatory=true
    versionRange="[0.5.0,)"
    ordering="AFTER"
    side="BOTH"